Only run summarize-rspec-tests when there are test results

diff --git a/semaphore/.semaphore/bin/summarize-rspec-tests b/semaphore/.semaphore/bin/summarize-rspec-tests
--- a/semaphore/.semaphore/bin/summarize-rspec-tests
+++ b/semaphore/.semaphore/bin/summarize-rspec-tests
@@ -1,3 +1,8 @@
 #!/usr/bin/env -S bash -e
 
+if [[ ! -d test-summaries ]]; then
+  echo "ERROR: no test results found"
+  exit 1
+fi
+
 test-results publish test-summaries --parser rspec
